### PR TITLE
Fixes #62

### LINKED ISSUE #62: group-by on numeric data with calibration
I've only tested this with `cal_plot_breaks()` but grouping by a numeric variable fails. 

``` r
library(tidymodels)
library(probably)
#> 
#> Attaching package: 'probably'
#> The following objects are masked from 'package:base':
#> 
#>     as.factor, as.ordered
```

``` r

tidymodels_prefer()
theme_set(theme_bw())
options(pillar.advice = FALSE, pillar.min_title_chars = Inf)
```

``` r

set.seed(1)
tr_dat <- sim_classification(1000)
te_dat <- sim_classification(1000)

set.seed(2)
folds <- vfold_cv(tr_dat)
```

``` r

svm_spec <- svm_rbf(rbf_sigma = tune()) %>% set_mode("classification")

ctrl <- control_grid(save_pred = TRUE)
cls_metrics <- metric_set(brier_class, roc_auc, mcc)
grid <- tibble(rbf_sigma = 10^c(-5:-3))

set.seed(3)
svm_res <-
  svm_spec %>%
  tune_grid(
    class ~ .,
    resamples = folds,
    control = ctrl,
    metrics = cls_metrics,
    grid = grid
  )
```

``` r

best_two <-
  show_best(svm_res, metric = "brier_class", n = 2) %>%
  select(rbf_sigma, .config)
```

``` r

svm_pred <- collect_predictions(svm_res, parameters = best_two)
svm_pred
#> # A tibble: 2,000 × 8
#>    id     .pred_class_1 .pred_class_2  .row rbf_sigma .pred_class class  .config
#>    <chr>          <dbl>         <dbl> <int>     <dbl> <fct>       <fct>  <chr>  
#>  1 Fold01         0.804       0.196      11   0.00001 class_2     class… Prepro…
#>  2 Fold01         0.114       0.886      15   0.00001 class_2     class… Prepro…
#>  3 Fold01         0.356       0.644      21   0.00001 class_2     class… Prepro…
#>  4 Fold01         0.676       0.324      25   0.00001 class_2     class… Prepro…
#>  5 Fold01         0.726       0.274      41   0.00001 class_2     class… Prepro…
#>  6 Fold01         0.978       0.0217     54   0.00001 class_2     class… Prepro…
#>  7 Fold01         0.992       0.00806    57   0.00001 class_2     class… Prepro…
#>  8 Fold01         0.156       0.844      66   0.00001 class_2     class… Prepro…
#>  9 Fold01         0.981       0.0194     80   0.00001 class_2     class… Prepro…
#> 10 Fold01         0.969       0.0309     89   0.00001 class_2     class… Prepro…
#> # … with 1,990 more rows

svm_pred %>%
  group_by(.config) %>%   # <- works
  cal_plot_breaks(class, .pred_class_1)
```

``` r

svm_pred %>%
  group_by(rbf_sigma) %>%   # <- doesn't
  cal_plot_breaks(class, .pred_class_1)
#> Error in `geom_ribbon()` at probably/R/cal-plot.R:425:4:
#> ! Problem while converting geom to grob.
#> ℹ Error occurred in the 4th layer.
#> Caused by error in `draw_group()`:
#> ! Aesthetics can not vary along a ribbon
```

<sup>Created on 2023-01-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by edgararuiz**
- Adds numeric to factor conversion step for plots
- Adds test

### CODE REVIEW

File: R/cal-plot.R [hunk 1]
```diff
@@ -408,6 +408,10 @@ binary_plot_impl <- function(tbl, x, y,
     }
     has_groups <- TRUE
     dplyr_group <- parse_expr(gp_vars)
+    grouping_var <- tbl[, gp_vars][[1]]
+    if(is.numeric(grouping_var)) {
+      tbl[, gp_vars] <- as.factor(grouping_var)
```
Comment (topepo) [inline R/cal-plot.R:413]:
```suggestion
      tbl[, gp_vars] <- as.factor(format(grouping_var))
```

Comment (topepo) [reply R/cal-plot.R:413]: Do we allow 2+ grouping variables? Should this use `across()` instead?

Comment (edgararuiz) [reply R/cal-plot.R]: At this point it only supports one grouping variable: https://github.com/tidymodels/probably/blob/407d6b5d167d2d65f24f23e033aad865e0d3ed5a/R/cal-plot.R#L407
