### PR TITLE
better message for estimation functions when the levels are incomplete or incorrect

### LINKED ISSUE #94: bad error message for the classification estimation
If users do not fully specify the `estimate` argument, it gives a misleading error message: 

``` r
library(tidymodels)
library(probably)
#> 
#> Attaching package: 'probably'
#> The following objects are masked from 'package:base':
#> 
#>     as.factor, as.ordered
library(bonsai)
```

``` r

tidymodels_prefer()
theme_set(theme_bw())
options(pillar.advice = FALSE, pillar.min_title_chars = Inf)
```

``` r

set.seed(1345)
cls_train <- sim_classification(1000)
cls_test  <- sim_classification( 500)
cls_calib <- sim_classification( 500)

set.seed(7378)
cls_rs <- vfold_cv(cls_train)
```

``` r

lgb_spec <- boost_tree() %>% set_mode("classification") %>% set_engine("lightgbm")
```

``` r

cls_metrics <- metric_set(brier_class, roc_auc)

set.seed(6929)
lgb_res <-
  lgb_spec %>%
  fit_resamples(
    class ~ .,
    resamples = cls_rs,
    control = control_resamples(save_pred = TRUE),
    metrics = cls_metrics
  )
```

``` r

df_pred_res  <- lgb_res %>% collect_predictions()
```

``` r

df_est <-   
  df_pred_res %>%
  cal_estimate_logistic(truth = class, estimate = .pred_class_1)
#> Error in `stop_multiclass()` at probably/R/cal-estimate-logistic.R:139:4:
#> ! Multiclass not supported...yet
```

<sup>Created on 2023-03-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by topepo**
Closes #94 

Different error messages: 

``` r
library(tidymodels)
library(probably)
#> 
#> Attaching package: 'probably'
#> The following objects are masked from 'package:base':
#> 
#>     as.factor, as.ordered
```

``` r

tidymodels_prefer()
theme_set(theme_bw())
options(pillar.advice = FALSE, pillar.min_title_chars = Inf)
```

``` r

# Previously, these both gave errors of '! Multiclass not supported...yet'

# The estimate function didn't specify all prediction columns: 
segment_logistic %>% cal_estimate_logistic(truth = Class, estimate = .pred_poor)
#> Error in `check_level_consistency()`:
#> ! We can't connect the specified prediction columns to some factor levels (good). The selected columns were .pred_poor. Are there more columns to add in the funciton call?
#> Backtrace:
#>     ▆
#>  1. ├─segment_logistic %>% ...
#>  2. ├─probably::cal_estimate_logistic(., truth = Class, estimate = .pred_poor)
#>  3. └─probably:::cal_estimate_logistic.data.frame(...)
#>  4.   └─probably:::cal_logistic_impl(...)
#>  5.     └─probably:::truth_estimate_map(...)
#>  6.       └─probably:::check_level_consistency(truth_levels, est_map)
#>  7.         └─rlang::abort(msg)

# (Incomplete specification of the columns _does_ work with the plot funcitons tho)

# Added better error for logistic with 3+ classes
hpc_cv %>% cal_estimate_logistic(truth = obs, estimate = c(VF:L))
#> Error in `cal_logistic_impl()`:
#> ! The number of outcome factor levels isn't consistent with the calibration method. The levels were: 'VF', 'F', 'M', 'L'
#> Backtrace:
#>     ▆
#>  1. ├─hpc_cv %>% ...
#>  2. ├─probably::cal_estimate_logistic(., truth = obs, estimate = c(VF:L))
#>  3. └─probably:::cal_estimate_logistic.data.frame(., truth = obs, estimate = c(VF:L))
#>  4.   └─probably:::cal_logistic_impl(...)
#>  5.     └─rlang::abort(msg)
```

<sup>Created on 2023-05-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I've also updated the docs to say when we extend binary methods to multiclass.

### CODE REVIEW

File: R/cal-estimate-logistic.R [hunk 1]
```diff
@@ -136,7 +144,10 @@ cal_logistic_impl <- function(.data,
       source_class = source_class
     )
   } else {
-    stop_multiclass()
+    msg <- paste("The number of outcome factor levels isn't consistent with",
+                 "the calibration method. The levels were:",
+                 paste0("'", levels, "'", collapse = ", "))
```
Comment (EmilHvitfeldt) [inline R/cal-estimate-logistic.R:149]: The error should mention what the expected number of levels should be

```suggestion
    msg <- paste("The number of outcome factor levels isn't consistent with",
                 "the calibration method. Only two class `truth` factors are",
                 "allowed. The given levels were:",
                 paste0("'", levels, "'", collapse = ", "))
```

File: R/cal-utils.R [hunk 2]
```diff
@@ -38,11 +38,34 @@ truth_estimate_map <- function(.data, truth, estimate) {
...
+  if (any(null_map) | length(lvls) != length(mapping)) {
+    missings <- lvls[null_map]
+    missings <- paste0(missings, collapse = ", ")
+    cols <- mapping[!null_map]
+    cols < purrr::map_chr(cols, as.character)
+    cols <- paste0(cols, collapse = ", ")
+    msg <- paste0(
+      "We can't connect the specified prediction columns to some factor levels (",
+      missings, "). The selected columns were ", cols, ". Are there more ",
+      "columns to add in the funciton call?"
```
Comment (EmilHvitfeldt) [inline R/cal-utils.R:65]:
```suggestion
      "columns to add in the function call?"
```

**Review by EmilHvitfeldt — APPROVED** [review]
looking good. 2 comments
